@url = https://miniature-train-w6j697rxw7939gvw-8080.app.github.dev/

POST {{url}}/auth
Content-Type: application/json

{
    "nomeDeUsuario" : "admin",
    "senha" : "admin"
}

#{
#    "nomeDeUsuario" : "teste",
#    "senha" : "testando"
#}
