@url = https://miniature-train-w6j697rxw7939gvw-8080.app.github.dev/

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJGQVRFQyBBUEkiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTc0NTg3NzAzM30.X0Dac6w7jm7qrwbpjL_F62m1ILzikuz8EijqIWm1HWs

GET {{url}}/categorias
Authorization:  Bearer {{token}}

###
POST {{url}}/categorias
Authorization:  Bearer {{token}}
Content-Type: application/json

{
    "nome" : "Ciencias Exatas"
}