@url = https://miniature-train-w6j697rxw7939gvw-8080.app.github.dev/
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJGQVRFQyBBUEkiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTc0NTk2NjcwMH0.wVi6zHweZ14LB265IqOKEzKL1Z4H8Gbrrbciz0wrbXk

POST {{url}}/usuarios
Authorization:  Bearer {{token}}
Content-Type: application/json

{
    "nomeDeUsuario" : "teste",
    "senha" : "testando"
}